dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.6.0
  # - witnet/elliptic-curve-solidity@0.2.1
compiler:
  solc:
    optimizer:
      details:
        cse: true
        yul: true
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.6.0'
      # - '@ecc=witnet/elliptic-curve-solidity@0.2.1'
wallets:
  from_key: ${PRIVATE_KEY}
networks:
  default: development
  rinkeby:
    verify: True
  kovan:
    verify: True
  development:
    verify: False
  ganache-local:
    verify: False
dotenv: .env