dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.6.0
compiler:
  solc:
    optimizer:
      details:
        cse: true
        yul: true
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.6.0'
wallets:
  from_key: ${PRIVATE_KEY}
networks:
  default: development
  rinkeby:
    verify: True
  kovan:
    verify: True
  development:
    verify: False
  ganache-local:
    verify: False
dotenv: .env